name = "Diffractor"
uuid = "9f5e2b26-1114-432f-b630-d3fe2085c51c"
authors = ["Keno Fischer <keno@juliacomputing.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
